name: chatereum-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          touch .env
          echo JWT_SECRET = ChAtErEuM@2022*2023 >> .env
          echo DB_NAME=chatereum >> .env
          echo DB_USERNAME=arjis >> .env
          echo DB_PASSWORD=chatereumSQL@2022 >> .env
          echo DB_HOST=api.chatereum.ml >> .env
          cat .env
          pm2 restart app
          pm2 save
          pm2 startup
