name: chatereum-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: 
          sudo npm install
          sudo pm2 stop 0
          sudo pm2 start 0
          sudo pm2 save
          sudo pm2 startup
